sonar.projectKey=vulnerablemart-api
sonar.projectName=VulnerableMart API
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/tests/**, **/node_modules/**, **/.git/**, **/k8s/**
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
